### ISSUE TITLE
MVP wireframe

### ISSUE THREAD

**Issue by emcclosky** [aaronArinder/welby#22]
#### Problem
Need a visual guide for the framework of the mvp view. 

#### Solution
Mockup a wireframe for the mvp.

#### To-dos
- [x]  Design basic layout
- [x]  Plan functionality

**Comment by aaronArinder** [comment]
This is more of an exercise in planning things than generating something that will guide development. The wireframe for the home screen, where dispositions are inputted, is below. Functionally, we've already planned out how this will work: take a disposition and context in, timestamp it, and persist it. 

![1548371956_1819_24012019_348x652](https://user-images.githubusercontent.com/26738844/51714867-a1526380-2004-11e9-9afb-f118aff664fe.png)
